# Connexion base de donnees - variables Railway (postgres_db)
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

server.ssl.enabled=false
server.port=${PORT:8080}

redis.enabled=${REDIS_ENABLED:false}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

pair.seed.reference-data.enabled=true
pair.seed.demo-data.enabled=true