FROM pgvector/pgvector:pg16

# L'image pgvector/pgvector inclut déjà pgvector.
# On ajoute PostGIS par-dessus.
RUN apt-get update && apt-get install -y \
    postgresql-16-postgis-3 \
    postgresql-16-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

COPY init-extensions.sql /docker-entrypoint-initdb.d/