package org.program.pair.domain.notification;

public enum NotificationType {
    NEW_MESSAGE,
    NEW_MATCH,
    NEARBY_PROGRAM,
    NEW_FOLLOWER,
    PEER_RECOMMENDATION,
    PROGRAM_REVIEW,
    BADGE_EARNED,
    PROGRAM_REMINDER,
    PROGRESSION_REMINDER,
    ACCOUNT_VERIFICATION,
    PASSWORD_RESET,
    MODERATION_ACTION
}
