package org.program.pair.domain.notification;

public enum NotificationType {
    NEW_MESSAGE,
    NEW_MATCH,
    NEARBY_PROGRAM,
    NEW_FOLLOWER,
    PEER_RECOMMENDATION,
    PROGRAM_REVIEW,
    BADGE_EARNED,
    PROGRAM_REMINDER,
    PROGRESSION_REMINDER,
    ACCOUNT_VERIFICATION,
    PASSWORD_RESET,
    MODERATION_ACTION,
    AUTHOR_NEW_ACTIVITY,
    AUTHOR_NEW_PROGRAM,
    ACTIVITY_UPDATED,
    ACTIVITY_NEW_PROGRAM,
    CATEGORY_NEW_ACTIVITY
}
